#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanExplicitFeatures

rm -rf 0/*
rm -rf constant/triSurface/*.eMesh
rm -rf system/blockMeshDict system/surfaceFeaturesDict system/snappyHexMeshDict system/fvSchemes 
rm -rf system/decomposeParDict system/controlDict system/functions.py
if command -v foamListDynamicCode >/dev/null 2>&1; then
    foamListDynamicCode -case "$PWD" -rm || true 
fi
rm -rf dynamicCode

#------------------------------------------------------------------------------
